import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:printing/printing.dart';
import 'package:medicore/services/prescription_service.dart';

class PrescriptionPdfViewer extends StatefulWidget {
  final Uint8List previewBytes;
  final String doctorId;
  final String? doctorName;
  final String patientId;
  final List<Map<String, dynamic>> medicines;
  final String notes;
  final String? existingId; // set when editing an existing prescription

  const PrescriptionPdfViewer({
    super.key,
    required this.previewBytes,
    required this.doctorId,
    this.doctorName,
    required this.patientId,
    required this.medicines,
    required this.notes,
    this.existingId,
  });

  @override
  State<PrescriptionPdfViewer> createState() => _PrescriptionPdfViewerState();
}

class _PrescriptionPdfViewerState extends State<PrescriptionPdfViewer> {
  bool _uploading = false;

  Future<void> _upload() async {
    setState(() => _uploading = true);
    try {
      // Upload the already-generated bytes — no regeneration needed
      await PrescriptionService.uploadAndSavePrescription(
        bytes: widget.previewBytes,
        patientId: widget.patientId,
        medicines: widget.medicines,
        notes: widget.notes,
        doctorName: widget.doctorName,
        existingId: widget.existingId,
      );
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Prescription uploaded successfully'),
          backgroundColor: Colors.green,
        ),
      );
      Navigator.of(context).pop(true);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Upload failed: $e'),
          backgroundColor: Colors.red,
        ),
      );
    } finally {
      if (mounted) setState(() => _uploading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.existingId != null
            ? 'Preview (Edit)'
            : 'Prescription Preview'),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black87,
        elevation: 0,
        actions: [
          _uploading
              ? const Padding(
                  padding: EdgeInsets.all(14),
                  child: SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  ),
                )
              : TextButton.icon(
                  onPressed: _upload,
                  icon: const Icon(Icons.cloud_upload_rounded,
                      color: Color(0xFF667eea)),
                  label: const Text(
                    'Upload',
                    style: TextStyle(
                        color: Color(0xFF667eea), fontWeight: FontWeight.w700),
                  ),
                ),
        ],
      ),
      body: PdfPreview(
        build: (_) async => widget.previewBytes,
        allowPrinting: true,
        allowSharing: true,
        canChangePageFormat: false,
        canChangeOrientation: false,
      ),
    );
  }
}
