// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtnubKrAcvTHfkYzZ7qMAT7yY2d8AH_Tg',
    appId: '1:1091595125716:web:c8dd0c6d7eec99ef584c41',
    messagingSenderId: '1091595125716',
    projectId: 'medicore-73fde',
    authDomain: 'medicore-73fde.firebaseapp.com',
    storageBucket: 'medicore-73fde.firebasestorage.app',
    measurementId: 'G-2TYFHHSYWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgf_rEx6rQ6V_Au6VR-Nk7qaeyCFis5Og',
    appId: '1:1091595125716:android:f01023ba7af990f8584c41',
    messagingSenderId: '1091595125716',
    projectId: 'medicore-73fde',
    storageBucket: 'medicore-73fde.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6mqxQg3yoGeG4TAGbRyYVuHsyJYAY2G0',
    appId: '1:1091595125716:ios:117c524f3dcf293f584c41',
    messagingSenderId: '1091595125716',
    projectId: 'medicore-73fde',
    storageBucket: 'medicore-73fde.appspot.com',
    androidClientId:
        '1091595125716-4rk95f7mkp8l025r59ii80ruf3idqqgu.apps.googleusercontent.com',
    iosClientId:
        '1091595125716-afatqps7auntmq6gkf4uqu21ejv0gp67.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtnubKrAcvTHfkYzZ7qMAT7yY2d8AH_Tg',
    appId: '1:1091595125716:web:d7a678edda4bdb39584c41',
    messagingSenderId: '1091595125716',
    projectId: 'medicore-73fde',
    authDomain: 'medicore-73fde.firebaseapp.com',
    storageBucket: 'medicore-73fde.firebasestorage.app',
    measurementId: 'G-XLH12JZ9N8',
  );
}
